replicaCount: 2

image:
  repository: yacine78/taskmanager
  tag: 22
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  DB_HOST: galeradb-mariadb-galera.default.svc.cluster.local
  DB_USER: user
  DB_NAME: taskmanager

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m