apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: galeradb-mariadb-galera
                  key: mariadb-password