apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}  # Nombre de réplicas (instances) du backend
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Référence à l'image Docker
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000          # Port sur lequel l'application backend écoute
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}  # Variable d'environnement DB_HOST
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}  # Variable d'environnement DB_USER
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}  # Variable d'environnement DB_PASSWORD
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}  # Variable d'environnement DB_NAME