apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}  # Type de service LoadBalancer pour utiliser MetalLB
  selector:
    app: {{ .Chart.Name }}  # Sélecteur pour lier le service au déploiement
  ports:
    - port: {{ .Values.service.port }}  # Port externe du service (80)
      targetPort: 5000       # Port interne sur lequel l'application écoute